### PR TITLE
Updates from databio group

### PR DESCRIPTION
**Pull request by nsheff**

### CODE REVIEW

**Comment by nsheff** [comment]
@afrendeiro any interest in bringing these forks back into sync?

**Comment by nsheff** [comment]
See #7

**Comment by nsheff** [comment]
what are you planning to do with this?

**Comment by afrendeiro** [comment]
Ups didn't mean to close, but it did automatically when I deleted dev.
Now that dev is clean, let's add this.

**Review by afrendeiro — APPROVED** [review]
Looks great. Thank you so much @vreuter !

**Comment by afrendeiro** [comment]
Oh damn, I'm afraid the merge didn't work as I wanted. I merged with `--strategy-option theirs` and added a few changes I had made on top.
But why are alll commits assigned to me? :disappointed:

**Pull request merged**
