### PR TITLE
ngstk API agreement, chipseq as guinea pig for pypiper.Pipeline and checkpoint framework

### LINKED ISSUE #2: set_file_path error
Reported by @mtugrul

I was not able to run chipseq.py and atacseq.py in looper. The following error comes, I looked into the corresponding lines but did not understand why. Any help?

chipseq:
```
Traceback (most recent call last):
File "/home/mtugrul/software/pipelines/pipelines/chipseq.py", line 755, in
sys.exit(main())
File "/home/mtugrul/software/pipelines/pipelines/chipseq.py", line 473, in main
sample.set_file_paths()
File "/home/mtugrul/software/pipelines/pipelines/chipseq.py", line 78, in set_file_paths
super(ChIPseqSample, self).set_file_paths()
TypeError: set_file_paths() takes exactly 2 arguments (1 given)
```
atacseq:
```
Traceback (most recent call last):
File "/home/mtugrul/software/pipelines/pipelines/atacseq.py", line 723, in
sys.exit(main())
File "/home/mtugrul/software/pipelines/pipelines/atacseq.py", line 456, in main
sample.set_file_paths()
File "/home/mtugrul/software/pipelines/pipelines/atacseq.py", line 54, in set_file_paths
super(ATACseqSample, self).set_file_paths()
TypeError: set_file_paths() takes exactly 2 arguments (1 given)
```

ok, it looks like this problem is due to new looper versions. When I install looper v0.5, it seems to be running now. I tried with all other dev versions of looper v0.6, but no success! I will stick to v0.5 for now, but this should be solved in long term.

### LINKED ISSUE #4: Attribute reference to 'bigwig' on Sample in chipseq.py
In the `chipseq.py` pipeline, there are three usages of `sample.bigwig`, but the `Sample` instance being used does not have a `bigwig` attribute.
```
Target exists: `/sfs/lustre/allocations/shefflab/processed//kipnis_chip/micro/results_pipeline/input_12k/mapped/input_12k.trimmed.bowtie2.filtered.bam.bai`
Removed existing flag: /sfs/lustre/allocations/shefflab/processed//kipnis_chip/micro/results_pipeline/input_12k/chipseq_failed.flag
Traceback (most recent call last):
  File "/home/vpr9v/code/open_pipelines/pipelines/chipseq.py", line 757, in <module>
    sys.exit(main())
  File "/home/vpr9v/code/open_pipelines/pipelines/chipseq.py", line 484, in main
    process(sample, pipe_manager, args)
  File "/home/vpr9v/code/open_pipelines/pipelines/chipseq.py", line 642, in process
    track_dir = os.path.dirname(sample.bigwig)
AttributeError: 'ChIPseqSample' object has no attribute 'bigwig'

Pypiper terminating spawned child process 190059

Change status from running to failed
```

### PR DESCRIPTION
**Pull request by vreuter**
Some now-unused code lingers in `chipseq.py`, but I think it should remain until the newer version get some more in-the-wild testing.
Close #2 
Close #4

### CODE REVIEW

**Comment by vreuter** [comment]
This now also includes some updates to the package setup that make installation possible with newer versions of pip/setuptools and related dependencies, and reflects the slight change in structure of this repo, particularly removal of the `config` directory

**Comment by afrendeiro** [comment]
Hey @vreuter this is shaping up very nicely!
I think `pypiper.Pipeline` is also quite a good idea.
I just had a general look but recently haven't had much time to follow closely. Will you let me know when things are at a point to review/test?

**Comment by vreuter** [comment]
Thanks! Yep, will do.

**Comment by vreuter** [comment]
Hey @afrendeiro I think whenever you're ready, this is set for review. Retained still is the original code for comparison in case anything breaks, but that can be removed once this has been used a bit more frequently/heavily and confidence increases. It's been working well in the last few runs, though, so it can be reviewed now.

**Pull request closed without merging**
